name = "SCTA"
uid = "8E704ECC-12EC-11EA-A6CA-D6DA930038A2"
version = 19
description = "Total Annihilation for Supreme Commander! Updated and bugfixed by Dragun123, with permission from Raevn, coding fix help from Balth."
author = "Raevn"
url = ""
icon = "/mods/SCTA/Core_Commander.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
