name = "SCTA Test"
uid = "SCTATEST-AABA-11EA-A6CA-D6DA930038A2"
version = 19
description = "Total Annihilation for Supreme Commander! Updated and bugfixed by Dragun101, with permission from Raevn, coding fix help from Balth. New Models from Gamma of TA Total Mayham and Madmax of FAF. Thank you to Senth Faction Reselect Code"
author = "Raevn Updated by Dragun."
icon = "/mods/SCTA-master/Core_Commander.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
conflicts = { }
before = { }
after = { }
